
import { Material, Location, Language, TranslationSet, ForecastHorizon } from './types';

export const MATERIALS: Material[] = [
  { id: 'cement', name: { en: 'Cement', hi: 'सीमेंट', bn: 'সিমেন্ট' }, baseUnit: { en: 'bag', hi: 'बैग', bn: 'ব্যাগ' }, conversionFactors: [] },
  { id: 'steel', name: { en: 'TMT Steel', hi: 'टीएमटी स्टील', bn: 'টিএমটি স্টিল' }, baseUnit: { en: 'tonne', hi: 'टन', bn: 'টন' }, conversionFactors: [] },
  { id: 'fine-sand', name: { en: 'Fine Sand', hi: 'महीन रेत', bn: 'সূক্ষ্ম বালি' }, baseUnit: { en: 'cubic meter', hi: 'घन मीटर', bn: 'ঘন মিটার' }, conversionFactors: [{ toUnit: { en: 'tonne', hi: 'टन', bn: 'টন' }, factor: 1.6 }] },
  { id: 'coarse-sand', name: { en: 'Coarse Sand', hi: 'मोटी रेत', bn: 'মোটা বালি' }, baseUnit: { en: 'cubic meter', hi: 'घन मीटर', bn: 'ঘন মিটার' }, conversionFactors: [{ toUnit: { en: 'tonne', hi: 'टन', bn: 'টন' }, factor: 1.7 }] },
  { id: 'aggregate-10mm', name: { en: 'Aggregate (10mm)', hi: 'गिट्टी (10mm)', bn: 'অ্যাগ্রিগেট (10mm)' }, baseUnit: { en: 'cubic meter', hi: 'घन मीटर', bn: 'ঘন মিটার' }, conversionFactors: [{ toUnit: { en: 'tonne', hi: 'टन', bn: 'টন' }, factor: 1.5 }] },
  { id: 'aggregate-20mm', name: { en: 'Aggregate (20mm)', hi: 'गिट्टी (20mm)', bn: 'অ্যাগ্রিগেট (20mm)' }, baseUnit: { en: 'cubic meter', hi: 'घन मीटर', bn: 'ঘন মিটার' }, conversionFactors: [{ toUnit: { en: 'tonne', hi: 'टन', bn: 'টন' }, factor: 1.55 }] },
  { id: 'bricks', name: { en: 'Bricks', hi: 'ईंटें', bn: 'ইট' }, baseUnit: { en: '1000 units', hi: '1000 इकाइयां', bn: '1000 ইউনিট' }, conversionFactors: [] },
  { id: 'bitumen', name: { en: 'Bitumen VG-30', hi: 'बिटुमेन वीजी-30', bn: 'বিটুমেন ভিজি-৩০' }, baseUnit: { en: 'tonne', hi: 'टन', bn: 'টন' }, conversionFactors: [] },
  { id: 'paint', name: { en: 'Emulsion Paint', hi: 'इमल्शन पेंट', bn: 'ইমালশন পেইন্ট' }, baseUnit: { en: 'litre', hi: 'लीटर', bn: 'লিটার' }, conversionFactors: [] },
  { id: 'tiles', name: { en: 'Vitrified Tiles (600x600)', hi: 'विट्रिफाइड टाइल्स (600x600)', bn: 'विट्रिफाइड टाइल्स (600x600)' }, baseUnit: { en: 'sq meter', hi: 'वर्ग मीटर', bn: 'বর্গ মিটার' }, conversionFactors: [] },
  { id: 'cement-board', name: { en: 'Cement Board (8x4 ft)', hi: 'सीमेंट बोर्ड (8x4 फीट)', bn: 'সিমেন্ট বোর্ড (৮x৪ ফুট)' }, baseUnit: { en: 'sheet', hi: 'शीट', bn: 'শীট' }, conversionFactors: [] },
];

export const LOCATIONS: Location[] = [
  { id: 'kolkata', name: 'Kolkata' },
  { id: 'howrah', name: 'Howrah' },
  { id: 'durgapur', name: 'Durgapur' },
  { id: 'asansol', name: 'Asansol' },
  { id: 'siliguri', name: 'Siliguri' },
];

export const FORECAST_HORIZONS: { value: ForecastHorizon, labelKey: string }[] = [
    { value: 7, labelKey: 'horizon7' },
    { value: 15, labelKey: 'horizon15' },
    { value: 30, labelKey: 'horizon30' },
    { value: 45, labelKey: 'horizon45' },
    { value: 180, labelKey: 'horizon180' },
];

export const MATERIAL_GST: Record<string, number> = {
  'cement': 18,
  'steel': 18,
  'fine-sand': 5,
  'coarse-sand': 5,
  'aggregate-10mm': 5,
  'aggregate-20mm': 5,
  'bricks': 12,
  'paint': 28,
  'bitumen': 18,
  'tiles': 18,
  'cement-board': 18,
};

export const RATE_PRESETS: Record<string, Record<string, number>> = {
  kolkata: {
    'cement': 360,
    'steel': 62000,
    'fine-sand': 1300,
    'coarse-sand': 1200,
    'aggregate-10mm': 1600,
    'aggregate-20mm': 1500,
    'bricks': 8500,
    'bitumen': 45000,
    'paint': 250,
    'tiles': 400,
    'cement-board': 1200,
  },
  howrah: {
    'cement': 355,
    'steel': 61500,
    'fine-sand': 1280,
    'coarse-sand': 1180,
    'aggregate-10mm': 1580,
    'aggregate-20mm': 1480,
    'bricks': 8400,
    'bitumen': 44800,
    'paint': 245,
    'tiles': 395,
    'cement-board': 1180,
  },
  durgapur: {
    'cement': 340,
    'steel': 59000,
    'fine-sand': 1100,
    'coarse-sand': 1000,
    'aggregate-10mm': 1400,
    'aggregate-20mm': 1300,
    'bricks': 7800,
    'bitumen': 43000,
    'paint': 230,
    'tiles': 380,
    'cement-board': 1100,
  },
  asansol: {
    'cement': 335,
    'steel': 58500,
    'fine-sand': 1050,
    'coarse-sand': 950,
    'aggregate-10mm': 1350,
    'aggregate-20mm': 1250,
    'bricks': 7700,
    'bitumen': 42500,
    'paint': 225,
    'tiles': 375,
    'cement-board': 1080,
  },
  siliguri: {
    'cement': 370,
    'steel': 63000,
    'fine-sand': 1400,
    'coarse-sand': 1300,
    'aggregate-10mm': 1700,
    'aggregate-20mm': 1600,
    'bricks': 9000,
    'bitumen': 46000,
    'paint': 260,
    'tiles': 410,
    'cement-board': 1250,
  }
};


export const TRANSLATIONS: Record<Language, TranslationSet> = {
  en: {
    // Tabs
    forecasterTab: 'Material Forecaster',
    schedulerTab: 'Project Scheduler',
    cashFlowTab: 'Cash Flow',
    costEstimatorTab: 'Cost Estimator',
    
    // Forecaster
    title: 'Material Price Forecaster',
    subtitle: 'Select a material, location, and time horizon to generate a price forecast.',
    materialLabel: 'Material',
    locationLabel: 'Location',
    horizonLabel: 'Forecast Horizon',
    loadPresetsButton: 'Load Presets',
    horizon7: '7 Days',
    horizon15: '15 Days',
    horizon30: '30 Days',
    horizon45: '45 Days',
    horizon180: '6 Months',
    generateButton: 'Generate Forecast',
    loadingButton: 'Generating...',
    traditionalTitle: 'Rule-based Result',
    aiTitle: 'AI-Enhanced Suggestions',
    pricePerUnit: 'Price in',
    commentary: 'Commentary',
    errorTitle: 'Error',
    chartTitle: 'Price Forecast',
    historical: 'Historical',
    traditional: 'Traditional',
    ai_enhanced: 'AI Enhanced',
    price: 'Price',
    period: 'Period',
    noData: 'Generate a forecast to see results.',
    livePricesTitle: "Today's Market Prices",
    livePricesSubtitle: "Live rates from key suppliers in the region.",
    yourRatesTitle: "Your Landed Costs",
    rate: "Rate",
    unit: "Unit",
    landedCost: "Landed Cost",
    baseRate: "Base Rate",
    freight: "Freight",
    gst: "GST (%)",
    otherCharges: "Other Charges",
    editRates: "Edit Rates",
    save: "Save",
    convertedPrices: "Converted Prices",
    procurementTitle: "Procurement Assistant",
    procurementSubtitle: "Let AI find the best local suppliers for {material} based on today's market.",
    findSuppliersButton: "Find Suppliers",
    findingSuppliersButton: "Searching...",
    supplier: "Supplier",
    rating: "Rating",
    contact: "Contact",
    noSuppliersFound: "No suppliers were found for this material and location.",
    boqTitle: "Project Bill of Quantities (BOQ)",
    quantity: "Quantity",
    totalLandedCost: "Total Material Cost",
    saveDetailsButton: "Save Details",
    procurementPlanTitle: "AI Procurement Plan",
    totalCost: "Estimated Total Cost",
    recommendation: "Recommendation",
    reasoning: "Reasoning",
    buyNow: "Buy Now",
    wait: "Wait",
    splitBuy: "Split Buy",
    exportPlan: "Export Plan",

    // Scheduler
    schedulerTitle: "Project Schedule (CPM)",
    schedulerSubtitle: "Enter tasks, durations, and dependencies to calculate the critical path.",
    addTask: "Add Task",
    calculateSchedule: "Calculate Schedule",
    calculating: "Calculating...",
    taskName: "Task Name",
    duration: "Duration (days)",
    dependencies: "Dependencies (IDs)",
    taskTableTitle: "Task List",
    resultsTableTitle: "Schedule Results (CPM)",
    ES: "ES",
    EF: "EF",
    LS: "LS",
    LF: "LF",
    float: "Float",
    critical: "Critical",
    projectDuration: "Total Project Duration",
    days: "days",
    aiScheduleRiskTitle: "AI-Powered Risk Analysis",
    analyzeRisk: "Analyze Risks",
    analyzing: "Analyzing...",
    risk: "Potential Risk",
    impact: "Impact",
    mitigation: "Mitigation Suggestion",

    // Cash Flow
    cashFlowTitle: "Cash Flow Predictor",
    cashFlowSubtitle: "Manage your project's income and expenses to forecast your cash balance.",
    initialBalance: "Initial Cash Balance",
    addItem: "Add Item",
    description: "Description",
    amount: "Amount",
    date: "Date",
    type: "Type",
    income: "Income",
    expense: "Expense",
    cashFlowChartTitle: "Projected Cash Balance",
    aiPaymentRiskTitle: "AI Payment Delay Analysis",
    analyzePayments: "Analyze Payment Risks",

    // Cost Estimator
    costEstimatorTitle: "Project Cost Estimator",
    costEstimatorSubtitle: "Calculate your total project cost based on materials, labor, and other expenses.",
    costCategory: "Cost Category",
    materials: "Materials (from BOQ)",
    labor: "Labor",
    overheads: "Overheads & Equipment",
    contingency: "Contingency",
    totalProjectCost: "Total Estimated Project Cost",
    getAiContingency: "Get AI Suggestion",

    footer: {
      builtFor: 'Built for the Indian Market | IS-code Aligned Principles',
      disclaimer: 'Forecasts are estimates and not financial advice.'
    }
  },
  hi: {
    // Tabs
    forecasterTab: 'सामग्री भविष्यवक्ता',
    schedulerTab: 'परियोजना अनुसूचक',
    cashFlowTab: 'नकद प्रवाह',
    costEstimatorTab: 'लागत अनुमानक',

    title: 'सामग्री मूल्य भविष्यवक्ता',
    subtitle: 'मूल्य पूर्वानुमान बनाने के लिए एक सामग्री, स्थान और समय सीमा चुनें।',
    materialLabel: 'सामग्री',
    locationLabel: 'स्थान',
    horizonLabel: 'पूर्वानुमान क्षितिज',
    loadPresetsButton: 'प्रीसेट लोड करें',
    horizon7: '7 दिन',
    horizon15: '15 दिन',
    horizon30: '30 दिन',
    horizon45: '45 दिन',
    horizon180: '6 महीने',
    generateButton: 'पूर्वानुमान बनाएं',
    loadingButton: 'बनाया जा रहा है...',
    traditionalTitle: 'नियम-आधारित परिणाम',
    aiTitle: 'एआई-उन्नत सुझाव',
    pricePerUnit: 'मूल्य में',
    commentary: 'टीका',
    errorTitle: 'त्रुटि',
    chartTitle: 'मूल्य पूर्वानुमान',
    historical: 'ऐतिहासिक',
    traditional: 'पारंपरिक',
    ai_enhanced: 'एआई उन्नत',
    price: 'मूल्य',
    period: 'अवधि',
    noData: 'परिणाम देखने के लिए पूर्वानुमान बनाएं।',
    livePricesTitle: 'आज के बाजार मूल्य',
    livePricesSubtitle: 'क्षेत्र के प्रमुख आपूर्तिकर्ताओं से लाइव दरें।',
    yourRatesTitle: "आपकी लैंडेड लागतें",
    rate: "दर",
    unit: "इकाई",
    landedCost: "पहुँच लागत",
    baseRate: "आधार दर",
    freight: "भाड़ा",
    gst: "जीएसटी (%)",
    otherCharges: "अन्य शुल्क",
    editRates: "दरें संपादित करें",
    save: "सहेजें",
    convertedPrices: "परिवर्तित मूल्य",
    procurementTitle: "अधिप्राप्ति सहायक",
    procurementSubtitle: "एआई को आज के बाजार के आधार पर {material} के लिए सर्वश्रेष्ठ स्थानीय आपूर्तिकर्ता खोजने दें।",
    findSuppliersButton: "आपूर्तिकर्ता खोजें",
    findingSuppliersButton: "खोजा जा रहा है...",
    supplier: "आपूर्तिकर्ता",
    rating: "रेटिंग",
    contact: "संपर्क",
    noSuppliersFound: "इस सामग्री और स्थान के लिए कोई आपूर्तिकर्ता नहीं मिला।",
    boqTitle: "परियोजना मात्रा विधेयक (BOQ)",
    quantity: "मात्रा",
    totalLandedCost: "कुल सामग्री लागत",
    saveDetailsButton: "विवरण सहेजें",
    procurementPlanTitle: "एआई अधिप्राप्ति योजना",
    totalCost: "अनुमानित कुल लागत",
    recommendation: "सिफारिश",
    reasoning: "तर्क",
    buyNow: "अभी खरीदें",
    wait: "प्रतीक्षा करें",
    splitBuy: "विभाजित खरीद",
    exportPlan: "योजना निर्यात करें",

    // Scheduler
    schedulerTitle: "परियोजना अनुसूची (CPM)",
    schedulerSubtitle: "महत्वपूर्ण पथ की गणना करने के लिए कार्य, अवधि और निर्भरता दर्ज करें।",
    addTask: "कार्य जोड़ें",
    calculateSchedule: "अनुसूची की गणना करें",
    calculating: "गणना हो रही है...",
    taskName: "कार्य का नाम",
    duration: "अवधि (दिन)",
    dependencies: "निर्भरता (आईडी)",
    taskTableTitle: "कार्य सूची",
    resultsTableTitle: "अनुसूची परिणाम (CPM)",
    ES: "ES",
    EF: "EF",
    LS: "LS",
    LF: "LF",
    float: "फ्लोट",
    critical: "महत्वपूर्ण",
    projectDuration: "कुल परियोजना अवधि",
    days: "दिन",
    aiScheduleRiskTitle: "एआई-संचालित जोखिम विश्लेषण",
    analyzeRisk: "जोखिमों का विश्लेषण करें",
    analyzing: "विश्लेषण हो रहा है...",
    risk: "संभावित जोखिम",
    impact: "प्रभाव",
    mitigation: "शमन सुझाव",

    // Cash Flow
    cashFlowTitle: "नकद प्रवाह भविष्यवक्ता",
    cashFlowSubtitle: "अपने नकदी शेष का पूर्वानुमान लगाने के लिए अपनी परियोजना की आय और व्यय का प्रबंधन करें।",
    initialBalance: "प्रारंभिक नकद शेष",
    addItem: "आइटम जोड़ें",
    description: "विवरण",
    amount: "राशि",
    date: "तारीख",
    type: "प्रकार",
    income: "आय",
    expense: "व्यय",
    cashFlowChartTitle: "अनुमानित नकद शेष",
    aiPaymentRiskTitle: "एआई भुगतान विलंब विश्लेषण",
    analyzePayments: "भुगतान जोखिमों का विश्लेषण करें",

    // Cost Estimator
    costEstimatorTitle: "परियोजना लागत अनुमानक",
    costEstimatorSubtitle: "सामग्री, श्रम और अन्य खर्चों के आधार पर अपनी कुल परियोजना लागत की गणना करें।",
    costCategory: "लागत श्रेणी",
    materials: "सामग्री (BOQ से)",
    labor: "श्रम",
    overheads: "ओवरहेड्स और उपकरण",
    contingency: "आकस्मिकता",
    totalProjectCost: "कुल अनुमानित परियोजना लागत",
    getAiContingency: "एआई सुझाव प्राप्त करें",
    
    footer: {
      builtFor: 'भारतीय बाजार के लिए निर्मित | IS-कोड संरेखित सिद्धांत',
      disclaimer: 'पूर्वानुमान अनुमान हैं और वित्तीय सलाह नहीं हैं।'
    }
  },
  bn: {
    // Tabs
    forecasterTab: 'উপাদান পূর্বাভাসক',
    schedulerTab: 'প্রকল্প সময়সূচী',
    cashFlowTab: 'নগদ প্রবাহ',
    costEstimatorTab: 'খরচ অনুমানকারী',
    
    title: 'উপাদান মূল্য পূর্বাভাসক',
    subtitle: 'মূল্য পূর্বাভাসের জন্য একটি উপাদান, অবস্থান এবং সময় দিগন্ত নির্বাচন করুন।',
    materialLabel: 'উপাদান',
    locationLabel: 'অবস্থান',
    horizonLabel: 'পূর্বাভাস দিগন্ত',
    loadPresetsButton: 'প্রিসেট লোড করুন',
    horizon7: '৭ দিন',
    horizon15: '১৫ দিন',
    horizon30: '৩০ দিন',
    horizon45: '৪৫ দিন',
    horizon180: '৬ মাস',
    generateButton: 'পূর্বাভাস তৈরি করুন',
    loadingButton: 'তৈরি হচ্ছে...',
    traditionalTitle: 'নিয়ম-ভিত্তিক ফলাফল',
    aiTitle: 'এআই-উন্নত পরামর্শ',
    pricePerUnit: 'মূল্য',
    commentary: 'ভাষ্য',
    errorTitle: 'ত্রুটি',
    chartTitle: 'মূল্য পূর্বাভাস',
    historical: 'ঐতিহাসিক',
    traditional: 'ঐতিহ্যগত',
    ai_enhanced: 'এআই উন্নত',
    price: 'দাম',
    period: 'সময়কাল',
    noData: 'ফলাফল দেখতে একটি পূর্বাভাস তৈরি করুন।',
    livePricesTitle: 'আজকের বাজার দর',
    livePricesSubtitle: 'অঞ্চলের প্রধান সরবরাহকারীদের থেকে লাইভ রেট।',
    yourRatesTitle: "আপনার ল্যান্ডেড খরচ",
    rate: "দর",
    unit: "একক",
    landedCost: "ল্যান্ডেড খরচ",
    baseRate: "বেস রেট",
    freight: "মাল भाड़ा",
    gst: "জিএসটি (%)",
    otherCharges: "অন্যান্য চার্জ",
    editRates: "দর সম্পাদনা করুন",
    save: "সংরক্ষণ করুন",
    convertedPrices: "রূপান্তরিত মূল্য",
    procurementTitle: "ক্রয় सहायक",
    procurementSubtitle: "আজকের বাজারের উপর ভিত্তি করে {material} জন্য সেরা স্থানীয় সরবরাহকারী খুঁজে পেতে AI-কে দিন।",
    findSuppliersButton: "সরবরাহকারী খুঁজুন",
    findingSuppliersButton: "অনুসন্ধান চলছে...",
    supplier: "সরবরাহকারী",
    rating: "রেটিং",
    contact: "যোগাযোগ",
    noSuppliersFound: "এই উপাদান এবং অবস্থানের জন্য কোন সরবরাহকারী পাওয়া যায়নি।",
    boqTitle: "প্রকল্পের পরিমাণ বিল (BOQ)",
    quantity: "পরিমাণ",
    totalLandedCost: "মোট উপাদান খরচ",
    saveDetailsButton: "বিবরণ সংরক্ষণ করুন",
    procurementPlanTitle: "এআই সংগ্রহ পরিকল্পনা",
    totalCost: "আনুমানিক মোট খরচ",
    recommendation: "সুপারিশ",
    reasoning: "যুক্তি",
    buyNow: "এখনই কিনুন",
    wait: "অপেক্ষা করুন",
    splitBuy: "বিভক্ত ক্রয়",
    exportPlan: "পরিকল্পনা রপ্তানি করুন",

    // Scheduler
    schedulerTitle: "প্রকল্প সময়সূচী (CPM)",
    schedulerSubtitle: "গুরুত্বপূর্ণ পথ গণনা করতে কার্য, সময়কাল এবং নির্ভরতা লিখুন।",
    addTask: "কার্য যোগ করুন",
    calculateSchedule: "সময়সূচী গণনা করুন",
    calculating: "গণনা করা হচ্ছে...",
    taskName: "কার্যের নাম",
    duration: "সময়কাল (দিন)",
    dependencies: "নির্ভরতা (আইডি)",
    taskTableTitle: "কার্যের তালিকা",
    resultsTableTitle: "সময়সূচী ফলাফল (CPM)",
    ES: "ES",
    EF: "EF",
    LS: "LS",
    LF: "LF",
    float: "ফ্লোট",
    critical: "গুরুত্বপূর্ণ",
    projectDuration: "মোট প্রকল্পের সময়কাল",
    days: "দিন",
    aiScheduleRiskTitle: "এআই-চালিত ঝুঁকি বিশ্লেষণ",
    analyzeRisk: "ঝুঁকি বিশ্লেষণ করুন",
    analyzing: "বিশ্লেষণ করা হচ্ছে...",
    risk: "সম্ভাব্য ঝুঁকি",
    impact: "প্রভাব",
    mitigation: "প্রশমন প্রস্তাব",
    
    // Cash Flow
    cashFlowTitle: "নগদ প্রবাহ পূর্বাভাসক",
    cashFlowSubtitle: "আপনার নগদ ব্যালেন্স পূর্বাভাস দিতে আপনার প্রকল্পের আয় এবং ব্যয় পরিচালনা করুন।",
    initialBalance: "প্রাথমিক নগদ ব্যালেন্স",
    addItem: "আইটেম যোগ করুন",
    description: "বিবরণ",
    amount: "পরিমাণ",
    date: "তারিখ",
    type: "প্রকার",
    income: "আয়",
    expense: "ব্যয়",
    cashFlowChartTitle: "প্রক্ষিপ্ত নগদ ব্যালেন্স",
    aiPaymentRiskTitle: "এআই পেমেন্ট বিলম্ব বিশ্লেষণ",
    analyzePayments: "পেমেন্ট ঝুঁকি বিশ্লেষণ করুন",

    // Cost Estimator
    costEstimatorTitle: "প্রকল্প খরচ অনুমানকারী",
    costEstimatorSubtitle: "উপাদান, শ্রম এবং অন্যান্য খরচের উপর ভিত্তি করে আপনার মোট প্রকল্পের খরচ গণনা করুন।",
    costCategory: "খরচ বিভাগ",
    materials: "উপাদান (BOQ থেকে)",
    labor: "শ্রম",
    overheads: "ওভারহেড এবং সরঞ্জাম",
    contingency: "কন্টিনজেন্সি",
    totalProjectCost: "মোট আনুমানিক প্রকল্প খরচ",
    getAiContingency: "এআই পরামর্শ পান",

    footer: {
      builtFor: 'ভারতীয় বাজারের জন্য নির্মিত | IS-কোড সারিবদ্ধ নীতি',
      disclaimer: 'পূর্বাভাসগুলি অনুমান এবং আর্থিক পরামর্শ নয়।'
    }
  },
};
